"""Maps each of the 11 organ systems to the parameter names that belong to it.

Single source of truth: frontend/src/lib/organParamMap.ts — this file is
kept in lockstep with the FE map. Aliases (typos, casing, alternate names)
are normalised via the ALIASES dict below before lookup.
"""

# Display-canonical parameter names per organ. Keep in sync with
# frontend/src/lib/organParamMap.ts (run scripts/audit_param_sync.py to verify).
ORGAN_DEFINITIONS = [
    {
        "organ_name": 'Heart Health',
        "icon": '❤️',
        "display_order": 1,
        "gender": 'U',
        "params": [
            "agatston score (total)",
            "lad agatston score",
            "lad calcified plaques",
            "lad volume (mm\u00b3)",
            "lck agatston score",
            "lck calcified plaques",
            "lck volume (mm\u00b3)",
            "lm agatston score",
            "lm calcified plaques",
            "lm volume (mm\u00b3)",
            "rca agatston score",
            "rca calcified plaques",
            "rca volume (mm\u00b3)",
            "heart rate",
            "nt-probnp",
            "p-wave duration",
            "pericardium",
            "pr interval",
            "qrs duration",
            "qt interval (qtc)",
            "rhythm",
            "st segment",
            "apoa1",
            "apolipoprotein b",
            "hdl cholesterol",
            "hdl/ldl ratio",
            "homocysteine levels",
            "ldl cholesterol",
            "ldl/hdl ratio",
            "lipoprotein (a)",
            "non-hdl cholesterol",
            "total cholesterol",
            "total cholesterol / hdl",
            "triglycerides",
            "triglycerides / hdl",
            "vldl cholesterol",
        ],
    },
    {
        "organ_name": 'Endocrine & Hormonal Health',
        "icon": '⚡',
        "display_order": 2,
        "gender": 'U',
        "params": [
            "android fat",
            "android:gynoid ratio",
            "bmi",
            "body fat",
            "fat free mass",
            "fat mass index",
            "gynoid fat",
            "total fat mass",
            "trunk fat mass",
            "trunk:limb fat ratio",
            "visceral fat level",
            "visceral fat mass",
            "average blood glucose",
            "c-peptide",
            "fasting blood glucose",
            "hba1c",
            "homa-ir",
            "insulin",
            "ketone",
            "anti-tg",
            "reverse t3",
            "thyroid",
            "thyroid lesions",
            "thyroid volume",
            "thyroxine (t4) free",
            "tpo",
            "triiodothyronine (t3) free",
            "tsh",
            "adrenals",
            "cortisol",
            "dhea",
            "igf-1",
        ],
    },
    {
        "organ_name": 'Liver & Digestive Health',
        "icon": '🫀',
        "display_order": 3,
        "gender": 'U',
        "params": [
            "abdominal wall",
            "afp",
            "albumin",
            "alp",
            "alt",
            "amylase",
            "ast",
            "ast/alt ratio",
            "bilirubin (indirect)",
            "bilirubin direct",
            "bowel",
            "cardia",
            "cbd (common bile duct)",
            "cea",
            "extrahepatic biliary tree",
            "gall bladder content",
            "gallbladder pericholecystic region",
            "gallbladder size",
            "gallbladder wall",
            "ggt",
            "globulin",
            "hepatic veins",
            "intrahepatic biliary radicals",
            "lipase",
            "liver and digestive health: congenital causes",
            "liver and digestive health: degenerative",
            "liver and digestive health: infective-active",
            "liver and digestive health: inflammation",
            "liver and digestive health: ischemic causes",
            "liver and digestive health: post-infective",
            "liver and digestive health: tumours",
            "liver fat %",
            "liver outline & size",
            "liver parenchyma",
            "liver steatosis grade",
            "liver: focal changes",
            "liver: hepatic veins",
            "liver: portal vein",
            "nasopharynx",
            "oesophagus",
            "oropharynx",
            "pancreas duct",
            "pancreas outline",
            "pancreatic parenchyma",
            "parotid glands",
            "peri-rectal fat",
            "peripancreatic region",
            "periportal region",
            "perisplenic region",
            "peritoneum",
            "pt / inr",
            "rectum & rectosigmoid",
            "serum albumin/globulin",
            "spleen parenchyma",
            "spleen size & outline",
            "splenic hilum",
            "total bilirubin",
            "total protein",
        ],
    },
    {
        "organ_name": 'Brain & Mental Health',
        "icon": '🧠',
        "display_order": 4,
        "gender": 'U',
        "params": [
            "basal ganglia",
            "brain: congenital causes",
            "brain: degenerative",
            "brain: infective-active",
            "brain: ischemic causes",
            "brain: post-infective",
            "brain: tumours",
            "cerebral white matter",
            "frontal sinuses",
            "globes",
            "lacrimal glands",
            "maxillary sinuses",
            "meninges",
            "midbrain",
            "optic nerve",
            "orbital fat",
            "orbits",
            "paranasal sinuses",
            "pons",
            "veins",
            "ventricles",
            "white matter hyperintensity",
            "bone, muscle & joint health: congenital causes",
            "bone, muscle & joint health: degenerative",
            "bone, muscle & joint health: infective-active",
            "bone, muscle & joint health: inflammation",
            "bone, muscle & joint health: ischemic causes",
            "bone, muscle & joint health: post-infective",
            "bone, muscle & joint health: traumatic issues",
            "bone, muscle & joint health: tumours",
            "endocrine and metabolic health: congenital causes",
            "endocrine and metabolic health: degenerative",
            "endocrine and metabolic health: infective-active",
            "endocrine and metabolic health: inflammation",
            "endocrine and metabolic health: ischemic causes",
            "endocrine and metabolic health: post-infective",
            "endocrine and metabolic health: tumours",
            "heart health: congenital causes",
            "heart health: degenerative",
            "heart health: infective-active",
            "heart health: inflammation",
            "heart health: ischemic causes",
            "heart health: post-infective",
            "heart health: tumours",
            "kidney & urinary health: congenital causes",
            "kidney & urinary health: degenerative",
            "kidney & urinary health: infective-active",
            "kidney & urinary health: inflammation",
            "kidney & urinary health: ischemic causes",
            "kidney & urinary health: post-infective",
            "kidney & urinary health: traumatic issues",
            "kidney & urinary health: tumours",
        ],
    },
    {
        "organ_name": 'Kidney & Urinary Health',
        "icon": "\U0001fad8",
        "display_order": 5,
        "gender": 'U',
        "params": [
            "appearance",
            "bacteria",
            "bile pigment",
            "bile salt",
            "blood urea nitrogen (bun)",
            "bun / creatinine ratio",
            "casts",
            "chloride",
            "collecting system",
            "colour",
            "cortico-sinus signals",
            "creatinine",
            "creatinine urine",
            "crystals",
            "cystatin c",
            "egfr",
            "epithelial cells",
            "kidneys size, outline",
            "leucocyte esterase",
            "mucus",
            "nitrite",
            "other pelvic viscera",
            "parasite",
            "pelvic cavity",
            "pelvic lymphnodes",
            "pelvic soft tissues",
            "peri-renal fat",
            "peri-renal spaces",
            "ph",
            "potassium",
            "pth",
            "red blood cells",
            "renal cortical thickness",
            "retroperitoneum",
            "sodium",
            "specific gravity",
            "ua (uric acid)",
            "urea (calculated)",
            "urea/creatinine ratio",
            "ureters",
            "urinary bilirubin",
            "urinary bladder contents",
            "urinary bladder contour",
            "urinary bladder perivesical fat",
            "urinary bladder walls",
            "urinary glucose",
            "urinary leucocytes",
            "urinary microalbumin",
            "urinary protein",
            "urine albumin/creatinine",
            "urine blood",
            "urine ketone",
            "yeast",
        ],
    },
    {
        "organ_name": 'Blood, Immunity & Nutrition',
        "icon": '🩸',
        "display_order": 6,
        "gender": 'U',
        "params": [
            "rbc",
            "wbc",
            "hemoglobin",
            "hematocrit",
            "mcv",
            "rdw",
            "rdw-sd",
            "mch",
            "mchc",
            "platelet count",
            "plateletcrit (pct)",
            "mpv",
            "pdw",
            "plcr",
            "nucleated rbc",
            "nucleated rbc %",
            "immature granulocytes",
            "immature granulocytes %",
            "basophils",
            "basophils - count",
            "eosinophils",
            "eosinophils - count",
            "lymphocytes",
            "lymphocytes - count",
            "monocytes",
            "monocytes - count",
            "neutrophils",
            "neutrophils - count",
            "abdominal lymph nodes",
            "esr",
            "hs-crp",
            "ige",
            "left breast: lymphadenopathy",
            "right breast: lymphadenopathy",
            "neck lymphnodes",
            "ferritin",
            "iron",
            "iron % saturation",
            "tibc",
            "uibc",
            "calcium",
            "copper",
            "folate (b9)",
            "ldh",
            "magnesium, rbc",
            "selenium",
            "vitamin a",
            "vitamin b12",
            "vitamin d",
            "vitamin e",
            "zinc",
        ],
    },
    {
        "organ_name": 'Bone, Muscle & Joint Health',
        "icon": '🦴',
        "display_order": 7,
        "gender": 'U',
        "params": [
            "appendicular lean mass",
            "asmi",
            "cord, conus",
            "facets",
            "foramina",
            "lean mass",
            "mandible",
            "marrow signals",
            "maxilla",
            "mineral bone density (t-score)",
            "mineral bone density (z-score)",
            "paravertebral muscles",
            "phosphorus",
            "psoas muscles",
            "rsmi",
            "spinal canal",
            "spine curvature",
            "spine: discs",
            "spine: ligaments",
            "spine: signal intensities",
            "total lean mass",
            "trunk lean",
            "vertebral bodies",
            "vertebral body alignment",
        ],
    },
    {
        "organ_name": 'Lung & Respiratory Health',
        "icon": '🫁',
        "display_order": 8,
        "gender": 'U',
        "params": [
            "airway condition",
            "copd / emphysema",
            "glottis",
            "lung nodules & masses",
            "lung parenchyma",
            "lung vasculature",
            "lung volume",
            "mediastinal lymph nodes",
            "mediastinum & lymph nodes",
            "pleural cavities",
            "pleural space",
            "pneumonia / infection",
            "pulmonary fibrosis",
            "subglottis",
            "supra-glottis",
        ],
    },
    {
        "organ_name": 'Vascular Health',
        "icon": '🩺',
        "display_order": 9,
        "gender": 'U',
        "params": [
            "aorta and branches",
            "carotid cimt",
            "carotid plaque score",
            "iliac vessels",
            "ivc and tributaries",
            "mesentric vessels",
            "neck vessels",
            "other major vessels",
            "renal vessels",
            "splenic vessels",
            "superior venacava",
            "d-dimer",
            "fibrinogen",
        ],
    },
    {
        "organ_name": "Women's Health",
        "icon": '🌸',
        "display_order": 10,
        "gender": 'F',
        "params": [
            "amh",
            "breast",
            "breast density",
            "breast ultrasound",
            "ca 15-3",
            "ca-125",
            "cervix",
            "dhea-s",
            "endometrial thickness",
            "endometrium",
            "estradiol (e2)",
            "fsh",
            "he4",
            "hpv dna test",
            "left breast: architectural distortion",
            "left breast: asymmetry",
            "left breast: bi-rads category",
            "left breast: calcifications",
            "left breast: mass",
            "left breast: nipple retraction",
            "left breast: skin thickening",
            "lh",
            "mammography",
            "ovaries",
            "overall assessment",
            "pap smear",
            "pelvic ultrasound",
            "progesterone",
            "prolactin",
            "right breast: architectural distortion",
            "right breast: asymmetry",
            "right breast: bi-rads category",
            "right breast: calcifications",
            "right breast: mass",
            "right breast: nipple retraction",
            "right breast: skin thickening",
            "transvaginal ultrasound",
            "uterus",
        ],
    },
    {
        "organ_name": "Men's Health",
        "icon": '🔵',
        "display_order": 11,
        "gender": 'M',
        "params": [
            "free testosterone",
            "prostate",
            "prostate size (if male)",
            "prostate volume",
            "psa",
            "seminal vesicles",
            "shbg",
            "testosterone",
        ],
    },
]

# Param-name aliases — collapse synonyms, casing variants and typo forms
# into a single canonical name so admin findings match organ assignments
# regardless of which name was used at upload time. Mirrors the frontend
# ALIASES table in organParamMap.ts.
ALIASES = {
    # Calcium scoring — vendor reports break Agatston by vessel
    "agaston score": "agatston score (total)",
    "agatston score": "agatston score (total)",
    "lad agatston score": "agatston score (total)",
    "lck agatston score": "agatston score (total)",
    "lm agatston score": "agatston score (total)",
    "rca agatston score": "agatston score (total)",
    # Glucose
    "fbs": "fasting blood glucose",
    "glucose": "fasting blood glucose",
    "fasting glucose": "fasting blood glucose",
    "fasting blood sugar": "fasting blood glucose",
    "fasting blood glucose test": "fasting blood glucose",
    # Liver enzymes
    "alk phos": "alp",
    "alkaline phosphatase": "alp",
    # Inflammation
    "crp": "hs-crp",
    "c reactive protein": "hs-crp",
    "c-reactive protein": "hs-crp",
    # CBC differential twin pairs
    "lymph %": "lymphocytes - count",
    "lymphocyte %": "lymphocytes - count",
    "lymphocytes %": "lymphocytes - count",
    "lymphocyte percentage": "lymphocytes - count",
    "lymphocytes": "lymphocytes - count",
    "neutrophils": "neutrophils - count",
    "monocytes": "monocytes - count",
    "eosinophils": "eosinophils - count",
    "basophils": "basophils - count",
    "immature granulocytes %": "immature granulocytes",
    "nucleated rbc %": "nucleated rbc",
    # Lipids
    "non hdl cholesterol": "non-hdl cholesterol",
    "ldl/hdl ratio": "hdl/ldl ratio",
    # Vascular
    "aorta & branches": "aorta and branches",
    # MRI organ-prefixed variants
    "hepatic veins": "liver: hepatic veins",
    # Bone density spacing typo
    "mineral bone density(t-score)": "mineral bone density (t-score)",
    "mineral bone density(z-score)": "mineral bone density (z-score)",
    # Misc
    "leukocytes": "wbc",
    "prostate": "prostate size (if male)",
    "prostate volume": "prostate size (if male)",
}

def canon(s: str) -> str:
    """Return the canonical parameter name for `s` (lowercased + aliased)."""
    if not s: return ""
    k = s.lower().strip()
    return ALIASES.get(k, k)

RISK_LABELS = {
    "critical": "Urgent Medical Attention",
    "major": "High Health Risk",
    "minor": "Mild Health Concern",
    "normal": "Healthy and Stable",
}
